language: node_js

node_js:
  - 12

git:
  depth: false

services:
  - docker

before_install:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - npm install

script:
  - npm test
  - docker build . -t daocasino/sponsorship-provider:$TRAVIS_BRANCH


