language: node_js

node_js:
  - 12

git:
  depth: false

services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - npm test
  - docker build . -t daocasino/sponsorship-provider:$TRAVIS_BRANCH
  - |
    if [ $TRAVIS_BRANCH == "master" ]; then
      docker tag daocasino/sponsorship-provider:master daocasino/sponsorship-provider:latest
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push daocasino/sponsorship-provider:latest
    fi


